name: build-app

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string

env:
  JAVA_VERSION: "11.0.11"

jobs:
  echo-test:
    runs-on: ubuntu-latest
    steps:
      - name: show
        run: echo ${{ inputs.image-tag }}
