# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'profile'
        type: 'choice'
        required: true
        options:
          - 'dev'
          - 'stg'
          - 'prd'
      database:
        description: 'database'
        type: 'choice'
        required: true
        options:
          - test1
          - test2
      dir:
        description: 'Flywayコマンド'
        type: 'choice'
        required: true
        options:
          - 'migration,seed'
          - 'migration,seed,testdata'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: print dir
      run: |
        echo "${{github.event.inputs.dir}}"
        echo "${{github.event.inputs.branch}}"
        echo "${{github.ref}}"
