name: Call a reusable workflow

on:
  pull_request:
    types:
      - closed
    branches:
      - feat/test1

jobs:
  now:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.create-tag.outputs.tag }}
    steps:
      - name: time
        id: create-tag
        run: echo ::set-output name=tag::$( date "+%Y%m%d-%H%M%S" )

  call-workflow:
    needs: [now]
    uses: ryous0411/flyway-github-actions-sample/.github/workflows/build-app.yml@feat/test1
    with:
      image-tag: ${{ needs.now.outputs.tag }}
