name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: ryous0411/flyway-github-actions-sample/.github/workflows/build-app.yml@main
    with:
      app-name: "test"
      sid: "sample"
    secrets:
      ECR_AWS_REGION: ${{ secrets.ECR_AWS_REGION }}
