name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  now:
    runs-on: ubuntu-latest
    steps:
      - name: time
        id: create-tag
        run: echo ::set-output name=tag::$( date "+%Y%m%d-%H%M%S" )

  call-workflow:
    needs: [now]
    uses: ryous0411/flyway-github-actions-sample/.github/workflows/build-app.yml@main
    with:
      image-tag: ${{ needs.steps.create-tag.outputs.tag }}
