name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  now:
    runs-on: ubuntu-latest
    steps:
      - name: time
        run: echo "TAG=$( date "+%Y%m%d-%H%M%S" )" >> $GITHUB_ENV

  call-workflow:
    uses: ryous0411/flyway-github-actions-sample/.github/workflows/build-app.yml@main
    with:
      image-tag: ${{ env.TAG }}
